### ISSUE TITLE
 Update link on /Contribution_Manuals/BreatheCode_Writer.md

### ISSUE THREAD

**Issue by vicks1008** [breatheco-de/main-documentation#21]
URL for the link [Click here to see what you can enhance.](https://github.com/search?q=is%3Aopen+is%3Aissue+label%3Abc-writer) in the section **Enhancing documentation:** > **What kind of contributions do we expect as a BreatheCode Writer?** returns _We couldn’t find any issues matching 'is:open is:issue label:bc-writer'_

Search results page screenshot below!

![image](https://user-images.githubusercontent.com/10275211/48316416-6b7b1280-e5b1-11e8-9ffa-d9095fec8572.png)

**Comment by AJ-54** [comment]
I am updating the link

**Comment by AJ-54** [comment]
@vicks1008 @Yemh1  Kindly look at the changes proposed.

**Comment by alesanchezr** [comment]
Thanks man! 😄

**Comment by AJ-54** [comment]
@alesanchezr your welcome sir.
