### ISSUE TITLE
Create a test script that checks for broken links all the markdown files

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/main-documentation#24]
This repository will contain a lot of markdown documents and maybe some `json` or `txt` files.

We need a small script in any language that you like that scraps all the files and checks for broken links (404).

This task is not hard, the script will take no more than `100` lines, maybe it can be done in `5` lines depending on the programming language.

We will use the small script to automate the deployment of new manuals.

### If you know PHP

I know [this library does the job](https://github.com/emmanuelroecker/php-linkchecker) and [here is a sample script that actually used it](https://github.com/breatheco-de/assets/blob/master/test/syllabus-links.php).

Note: There other libraries in other languages if you search for "broken link checker" or something like that.

**Comment by kryptorado** [comment]
Can I work on this? Also, should the script search the text and json files or just the markdown?

**Comment by alesanchezr** [comment]
@kryptorado hey man, yes you can work on this. 

Markdown and json will be enough. Thanks!

**Comment by AJ-54** [comment]
Hey @alesanchezr , I would like to work on these .
Question : I will write in python , i want to know how to import the files in my code on which i need to perform tests.

**Comment by ashkmb** [comment]
@alesanchezr 
Hi,
is this issue still open? I would like to contribute if there is a spot for me.

**Comment by alesanchezr** [comment]
No man, this is done, thanks for offering! :)
