### ISSUE TITLE
Cohort attendancy percentage is wrong

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/main-documentation#40]
Hours: <hours>3</hours>

Here is an example of the attendance report:
https://attendancy.breatheco.de/?cohort_slug=madrid-pt-i&bc_token=8315769f680fd0e915077b16246850782c3c6dd0&assets_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjbGllbnRJZCI6MjIwLCJpYXQiOjE1OTA2Nzk4ODAsImV4cCI6MzMxNDc2MzE4ODB9.RJ0ZWxYz7f0vFveuhY9jbJ6AwRlJxs1lotPzDYL-myY

We need to fix the percentages, it says 300% but that is imposible. if you attend to every class its 100%, anything else is below 100%.

[This is the JSON](https://assets.breatheco.de/apis/activity/cohort/madrid-pt-i?activities=classroom_attendance,classroom_unattendance&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjbGllbnRJZCI6MjIwLCJpYXQiOjE1OTA2Nzk4ODAsImV4cCI6MzMxNDc2MzE4ODB9.RJ0ZWxYz7f0vFveuhY9jbJ6AwRlJxs1lotPzDYL-myY) that comes back with the attendance information.

The activities are: `classroom_attendance` and `classroom_unattendance`

This is the repository:
https://github.com/breatheco-de/attendancy

**Comment by alesanchezr** [comment]
Aprobado y por pagar.

**Comment by alesanchezr** [comment]
@Jtoledo88 pagaste esto?

**Comment by Jtoledo88** [comment]
se pagan este mes, a fin de mes, junto con el salario

**Comment by alesanchezr** [comment]
okok

**Comment by Jtoledo88** [comment]
Horas pagadas en junio
