### ISSUE TITLE
Link component for breathecode

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/main-documentation#42]
Hrs: <hrs>3</hrs>

Create a link component that accepts the following properties:

| Prop | Description |
| -------- | --------------|
| To          | If specified, it takes to a different reach router view |
| url          | If specified, it takes to a whole different website in a new tab by default (make sure to add rel nofollow noopener |
| color      | default is primary but can be: primary, success, danger, etc. (all bootstrap colors) |
| className | default is empty string `''` but can be any string |

The link component must include a [circuled blue arrow ](https://fontawesome.com/icons/arrow-circle-right?style=solid)by default in the props.color. The arrow must follow the component with to the right. The link text must be aligned to the left.

**Comment by alesanchezr** [comment]
Aprobado.

**Comment by Jtoledo88** [comment]
pagado
