### ISSUE TITLE
Button with Image Component

### ISSUE THREAD

**Issue by Omonroy36** [breatheco-de/main-documentation#43]
Hrs: <hrs>4</hrs>

Build a button that receives the following props (base use):
|  Prop | Description |
| ------------- | ------------- |
| imgSrc  | if specified, it takes an img source a displays it in the left side of the button, if not default avatar is set |
|  url  | If specified, it takes to a whole different website in a new tab by default (make sure to add rel nofollow noopener  |
|  to  | If specified, it takes to a different reach router view  |
|  className  | default will be set to primary, if passes a bootstrap it will set the button to that color |
|  sub  | if specified it will place a subtitle below the button title with a gray borded backgroud |

The button should always display the content justified to the left

![Captura](https://user-images.githubusercontent.com/33846362/89938869-1f755b80-dbe5-11ea-82d4-1fa9dbe54fa7.PNG)
@alesanchezr

**Comment by alesanchezr** [comment]
Que pasa si no tiene image? 
- Deberia salir el nombre sin el image.
- Que al igual que el sub, es opcional.
- Tambien deberias poder elegir el color del sub (primary, secondary...).

**Comment by alesanchezr** [comment]
Recuerda poner varios ejemplso

**Comment by alesanchezr** [comment]
Aprobado.

**Comment by Jtoledo88** [comment]
pagado
