### ISSUE TITLE
Syllabus builder

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/main-documentation#44]
Hrs <hrs>25<hrs>

Here is the repository: https://github.com/breatheco-de/syllabus-builder

The following is a proposal for an application that allows you to build a new course/program syllabus or edit an old one.
https://build.breatheco.de/

1. You can load a previous syllabus or start a new one.
2. You can set the basic syllabus information like course that it belongs to (dropdown), Title, Description, etc.
3. You can add more days to your syllabus.
4. On the left side you find all the possible things (projects, quiz, lesson, exercises).
5. You can drag & drop from the left to any day, that is how you build the syllabus.

![GMRdrcKsxY](https://user-images.githubusercontent.com/426452/90209269-f1e10b80-ddb8-11ea-8f90-c07aa9ae156d.gif)

We need a few thins:

- [ ] The application needs to be able to receive a token in the URL Querystring, that token will be use to make the requests to the breathecode.herokuapp.com API.
- [ ] If you add many days some data is lost, its not working properly, try adding lots of days and changing positions among then (swap day 1 and day 2 for example).
- [ ] We need to add a dropdown that lets pick a syllabus course and another dropdown for version number, this information will be coming from the API.
- [ ] Once the certificate AND the version its picked the entire syllabus loads on the screen.
- [ ] We need to add a "save" button that saves the syllabus on the API.
- [ ] On the syllabus version dropdown the user must be able to pick "new version".
- [ ] Do not remove the button to download the syllabus, the tacher should be able to download in a JSON as it is right now.
- [ ] Do not remoe the button to upload a syllabus from a JSON file.

Here is the documentation on how to add a new syllabus version or update a previous version:
https://documenter.getpostman.com/view/2432393/T1LPC6ef?version=latest#fe3a891c-2fc0-4e13-8f7a-124ea5b02d1c

**Comment by alesanchezr** [comment]
Se agregan 10 hrs mas, total: 25hrs. por differentes bugs que ha tenido que arreglar y para que corrija todo lo que sale en el PR:
https://github.com/breatheco-de/syllabus-builder/pull/1

**Comment by alesanchezr** [comment]
aprobado!

**Comment by Jtoledo88** [comment]
Pagadas a Jonathan Monroy en Diciembre

**Comment by Jtoledo88** [comment]
pay to @JMonroy86
