### ISSUE TITLE
Card component 

### ISSUE THREAD

**Issue by Omonroy36** [breatheco-de/main-documentation#49]
Hrs: <hrs>3</hrs>

Build a card component that displays descriptive information and can be used to redirect to another section of the app.

|  Prop | Description |
| ------------- | ------------- |
| img | If passed as a child it will display an image with a max-width and maintaining its aspect ratio  |
|  title  | if passed as a child it will be displayed as the title of the card with h5 tag and a font weight of 600  |
|  description  | if passe as a child it will be displayed as a description with a p tag  |
|  icon | if passed as a parameter it will display an icon floating always to the right, as default there will be a arrow icon  |
|  onClick  | if passed as a parameter it will make the whole card clickable and receive the function to trigger the action, as default the card is only informative |
|  variant  | if passed as a parameter it will change the background color of the card  |

It should look like this 
![Captura](https://user-images.githubusercontent.com/33846362/91344186-98f77700-e7ab-11ea-9181-3bf9da308942.PNG)

@alesanchezr

**Comment by alesanchezr** [comment]
No fue aprobado, requiere cambios que estan especificados en el PR: https://github.com/breatheco-de/client/pull/3

**Comment by alesanchezr** [comment]
@Omonroy36 como vas con esto?

**Comment by alesanchezr** [comment]
Aprobado.

**Comment by Jtoledo88** [comment]
Pagado
