### ISSUE TITLE
Certificates PDF Creation

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/main-documentation#50]
Hrs: <hrs>7<hrs>

The current certificate app, allows the dynamic generation of PDF certificates to print out for breathecode students.

In the new version we are going to connect with the new BreatheCode API, use this endpoint to review the certificate information:
https://breathecode.herokuapp.com/v1/certificate/token/59c413883ccf298e9b0d0bb855950420c7f3e94b/

Each certificate has a different token, the URL of the application must be like this:

certificate.breatheco.de/pdf/59c413883ccf298e9b0d0bb855950420c7f3e94b?lang=<language code>

- Note the `/pdf/` at the beginning of the URL, it means that this url will generate a PDF.
- Certificates can be translated live to any language (initialy english and spanish) using the querystring `lang` variable.
- The PDF certificates must be digitally signed (visible signature using a `Signature Font`).

**Comment by alesanchezr** [comment]
Aprobado @Jtoledo88

**Comment by alesanchezr** [comment]
Le agregue 4 horas mas (nates tenia 3, ahora tiene 7) porque se rehicieron los 2 diseño.

**Comment by Jtoledo88** [comment]
vale @alesanchezr  las pago hoy entonces.
