### ISSUE TITLE
Certificate landing page

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/main-documentation#52]
Hrs: <hrs>20</hrs>

1. When shared on social media it must follow the open graph principles (twitter, faceook and linkedin).
2. The picture to show on the social media its going to come on the API.
3. It needs to integrate with the [Breathecode Certificate API.](https://breathecode.herokuapp.com/v1/certificate/token/59c413883ccf298e9b0d0bb855950420c7f3e94b/) and get the certificate information from there.

![Screen Shot 2020-09-11 at 5 43 30 PM](https://user-images.githubusercontent.com/426452/92975477-58a82200-f456-11ea-8445-e47673f817f1.png)

**Comment by alesanchezr** [comment]
Voy a cambiar de 10 hrs a 20 hras porque ahora tienes que migrar el app a next.js, son 20 horas en total.

**Comment by alesanchezr** [comment]
- [x] Cambiar `/share/<token>` a `/<token>`
- [x] Cambiar `/` a `/find`
- [ ] Agregar a translations las cosas que usamos en los meta tags.
- [ ] Completar el share de linkedin, lo unico que tienes que hacer es abrir una pagina nueva que tenga el url de linkedin de share, y que tenga pre-congurado el `?url` en el querystring.
- [x] Utilizar `.env` y unificar todas las variables HOST para que vengan del `.env`, todos los `.env deben estar ignorados en gitignore menos el `.env.example` porque ese se usara como modelo para que futuros programadores puedan saber que variables deberían haber en cualquier .env, el `.env.example` tiene que tener valores de mentira, no vayas a agregar los de verdad, pero los nombres de las variables si son los correctos.
- [x] El download PDF tiene que abrir en una nueva ventanta.
- [ ] En la caja del "issues" el website deben venir de el API `data.academy.url`
- [ ] La descripción de el cerficado no se esta mostrando, debes agarrala de `specialty.description`
- [ ] La foto de la persona la sacas de `data.user.avatar_url`
- [ ] No esta agarrando la fecha de expiración, eso te lleva en `data.expires_at`
- [ ] El diseño del certificado llega por la propiedad `data.layout`

**Comment by alesanchezr** [comment]
aprobado.

**Comment by Jtoledo88** [comment]
Pagado
