### ISSUE TITLE
Students Voting page.

### ISSUE THREAD

**Issue by Omonroy36** [breatheco-de/main-documentation#54]
Hours: <hrs>6</hrs>

Build a page that allow students to give feedback about their sessions or classes. 
The page should look similar to this one.

![Captura](https://user-images.githubusercontent.com/33846362/95664776-5999a580-0b21-11eb-9d7a-7c60a3fc4c13.PNG)

The API end point is set to recieve the following information given by the student 

```
End point: /v1/feedback/answer/1

Body: {
    "commnet": "All good",
    "score": 2,
    "entity_type": "WORKSHOP",
    "entity_id": 2
}

```
The goal is to make it simple to use and validate edge cases. 

@alesanchezr

**Comment by alesanchezr** [comment]
Basado en el codigo que entregaste en [este repositorio](https://github.com/breatheco-de/nps):

- [x] **Esto ya lo acomode yo, haz pull del UPSTREAM:** Cuando utilizes variables de environment (`.env`) nadie que quiera instalar el proyecto puede adivinar que tiene que crear un archivo `.env`, entonces es mejor hacer commit de un `.env.example` que si este agregado al repositorio y que tenga un ejemplo (con valores ficticios por seguridad) de cada una de las variables que hay que declarar en el archivo. Tienes que asegurarte en el `.gitignore` que el .env.example si se incluya, que no este ignorado.

- [x] Cuando utilizas una variable de environment para los API requests es mejor solo colocar el host en la variable y no todo el endpoint, asi te aseguras de que puedas reusar la variable en otros requests.

- [x] Cada vez que hagas un fetch, debes manejar no solo el exito sino tambien el fracaso, si estas usando async/await tendras que utilizar `try/catch` para que cuando el enpoint falle puedas capiurar el error y mostrarle un mensaje al usuario.

- [x] Que pasa si no pongo token? deberias dar mensaje de error.

- [x] Que pasa si el numero de encuesta no existe? Deberias dar mensaje de error.

- [x] Que pasa si existe un token pero esta malo? Cuando se hace el request el servidor devuelve 400 pero el front-end no atrapa ese error y no dice nada, simplemente se muestra la mitad de la encuesta (todo menos la pregunta) y eso no esta bien, deberia ocultarse toda la pregunta y decir el error.

- [x] Que pasa si ya vote y vuelvo a enviar la votación? El mensaje de error que manda el servidor deberia mostrarse.

- [x] La confirmación del boton debe aparece solamente una vez que ya le di a enviar, no cuando hago hover: El usuario apreta enviar, luego el boton como fue apretado va a mostrar YES o NO, y luego si apreta en YES entonces se envia la votación.

- [x] Usaste react router, pero no colcoaste una ruta para cuando no hay ningun ID, es decir, si visito el home (sin colocar ID) me sale una pagina blanca, deberia decir que hace falta especificar el ID.

**Comment by alesanchezr** [comment]
Aprobado por 6 horas, eran 4 originales pero hicimos bastante back-n-forth.

**Comment by Jtoledo88** [comment]
Pagado
